dist: trusty
sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - libboost1.55-all-dev
env:
  global:
    - JOBS=2
    - LIBTORRENT_BRANCH=libtorrent-1_1_1
    - CC=gcc-6
    - CXX=g++-6
  matrix:
    - TEST_SUITE=unit
matrix:
  fast_finish: true
  include:
    - os: linux
      node_js: "6"
      env: TEST_SUITE=lint
before_install:
  - git clone --depth 1 -b $LIBTORRENT_BRANCH https://github.com/arvidn/libtorrent.git
  - cd libtorrent
  - ./autotool.sh
  - ./configure --prefix=$(pwd)/build --disable-static
  - make -j $JOBS
  - make install
  - export PKG_CONFIG_PATH=$(pwd)/build/lib/pkgconfig:$PKG_CONFIG_PATH
  - export LD_LIBRARY_PATH=$(pwd)/build/lib:$LD_LIBRARY_PATH
install: npm install
script: npm run $TEST_SUITE
